#!/usr/bin/env python3

lines = []
with open ('8D28.pdb','r') as file:
    line = file.readline()
    while line != '' :
        lines.append(line)
        line = file.readline()

for line in lines:
    if line[:4] =='ATOM':
        print(line)

